### ISSUE TITLE
How to distinguish the silent voice or unregistered voice with the registered voice?

### ISSUE THREAD

**Issue by leavessnow26** [FragJage/SpeakerVoiceIdentifier#3]
I find the 'probMax'  in function Gmm::Recogniser() can't distinguish the silent voice or unregistered voice with the registered voice. Is there any method to do that? Thanks

**Comment by FragJage** [comment]
To distinguish the silent voice, use a voice activity detection algorithm before SpeakerVoiceIdentifier. You can find more examples on github. For unregistered voice, i have no solution because Gmm is a classifier IA, so it absolutely wants to classify the voice, but i am not a IA specialist. If you find a solution, i am very interrested.
